import {useState, useMemo} from "react";
import {useMailCorrections} from "./mailCorrectionContext";
import {CorrectionStatusBadge} from "./MailCorrections";
import "./dashboard-mail.css";
import Pagination from "./Pagination";
import "./pagination.css";

export default function DashboardMail({role="Admin",userName="",open}){
  const{corrections}=useMailCorrections();
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(5);
  const rows=role==="Employee"?corrections.filter(x=>x.assignedEmployee.toLowerCase().includes("thangaraj")):role==="Quality Analyst"?corrections.filter(x=>["QC Pending","QC Rejected","Rework","QC Approved"].includes(x.status)):corrections;
  const paginatedRows = useMemo(() => rows.slice((page - 1) * pageSize, page * pageSize), [rows, page, pageSize]);
  const cards=role==="Employee"?[["My Corrections",rows.length,""],["Yet to Start",rows.filter(x=>x.status==="Allocated").length,"Allocated"],["Due Today",rows.filter(x=>x.dueAt.startsWith("2026-08-31")).length,""],["Work in Progress",rows.filter(x=>x.status==="Work in Progress").length,"Work in Progress"],["Waiting for Clarification",rows.filter(x=>x.status==="Waiting for Clarification").length,"Waiting for Clarification"],["QC Rejected",rows.filter(x=>x.status==="QC Rejected").length,"QC Rejected"],["Rework",rows.filter(x=>x.status==="Rework").length,"Rework"],["Completed Today",rows.filter(x=>["QC Approved","Closed"].includes(x.status)).length,"QC Approved"]]:[["Corrections Received Today",rows.filter(x=>x.receivedAt.startsWith("2026-08-31")).length,""],["Yet to Allocate",rows.filter(x=>x.status==="Yet to Allocate").length,"Yet to Allocate"],["Corrections in Progress",rows.filter(x=>x.status==="Work in Progress").length,"Work in Progress"],["Waiting for Clarification",rows.filter(x=>x.status==="Waiting for Clarification").length,"Waiting for Clarification"],["Correction QC Pending",rows.filter(x=>x.status==="QC Pending").length,"QC Pending"],["QC Rejected",rows.filter(x=>x.status==="QC Rejected").length,"QC Rejected"],["Overdue Corrections",rows.filter(x=>x.status==="Overdue").length,"Overdue"],["Delivered Today",rows.filter(x=>["Sent to Client","Closed"].includes(x.status)).length,"Sent to Client"]];
  return <div className="dashboard-mail"><div className="mc-summary">{cards.map(([x,n,s])=><button key={x} onClick={()=>open(s)}><span>{x}</span><b>{n}</b><small>Open corrections</small></button>)}</div><section className="panel mc-recent"><div><h3>{role==="Employee"?"My corrections":"Recent mail corrections"}</h3><p>Latest correction work and live status.</p></div><div className="scroll"><table><thead><tr><th>Correction ID</th><th>Project / ISBN</th><th>Chapter</th><th>Client</th><th>Round</th><th>Employee</th><th>Due date</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody>{paginatedRows.map(r=><tr key={r.id}><td><b>{r.id}</b></td><td><b>{r.projectName}</b><small>{r.isbn}</small></td><td>{r.chapter}</td><td>{r.client}</td><td>{r.correctionRound}</td><td>{r.assignedEmployee}</td><td>{new Date(r.dueAt).toLocaleDateString()}</td><td>{r.priority}</td><td><CorrectionStatusBadge status={r.status}/></td><td><button className="mc-link" onClick={()=>open("")}>Open</button></td></tr>)}</tbody></table></div>{rows.length>0&&<Pagination currentPage={page} totalItems={rows.length} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={setPageSize} pageSizeOptions={[5, 10, 20]} itemName="corrections"/>}</section></div>}
