import {useState, useMemo} from "react";
import {Download,Printer,RefreshCcw} from "lucide-react";
import {useMailCorrections} from "./mailCorrectionContext";
import "./mail-report.css";
import Pagination from "./Pagination";
import "./pagination.css";

export default function MailCorrectionReport(){
  const{corrections}=useMailCorrections();
  const[client,setClient]=useState(""),[status,setStatus]=useState(""),[employee,setEmployee]=useState(""),[generated,setGenerated]=useState(false);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const rows=corrections.filter(x=>!client||x.client===client).filter(x=>!status||x.status===status).filter(x=>!employee||x.assignedEmployee===employee);
  const completed=rows.filter(x=>["QC Approved","Sent to Client","Closed"].includes(x.status)).length,rejected=rows.filter(x=>["QC Rejected","Rework"].includes(x.status)).length,overdue=rows.filter(x=>x.status==="Overdue").length;
  const clientList = useMemo(() => [...new Set(rows.map(x=>x.client))], [rows]);
  const paginatedClients = useMemo(() => clientList.slice((page - 1) * pageSize, page * pageSize), [clientList, page, pageSize]);
  const csv=()=>{const data=[["ID","Client","Project","ISBN","Chapter","Employee","Round","Priority","Status","Received","Due"],...rows.map(x=>[x.id,x.client,x.projectName,x.isbn,x.chapter,x.assignedEmployee,x.correctionRound,x.priority,x.status,x.receivedAt,x.dueAt])].map(r=>r.map(v=>`"${v}"`).join(",")).join("\n");const u=URL.createObjectURL(new Blob([data],{type:"text/csv"}));const a=document.createElement("a");a.href=u;a.download="mail-correction-report.csv";a.click();URL.revokeObjectURL(u)};
  return <section className="panel mail-report"><div className="mail-report-head"><div><small>MAIL CORRECTION REPORT</small><h2>Correction analytics</h2><p>Generate live results from the shared correction records.</p></div></div><div className="mail-report-filters"><label>Client<select value={client} onChange={e=>{setClient(e.target.value);setPage(1);}}><option value="">All clients</option>{[...new Set(corrections.map(x=>x.client))].map(x=><option key={x}>{x}</option>)}</select></label><label>Employee<select value={employee} onChange={e=>{setEmployee(e.target.value);setPage(1);}}><option value="">All employees</option>{[...new Set(corrections.map(x=>x.assignedEmployee))].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{[...new Set(corrections.map(x=>x.status))].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="mail-report-buttons"><button className="primary" onClick={()=>{setGenerated(true);setPage(1);}}>Generate</button><button className="secondary" onClick={()=>{setClient("");setEmployee("");setStatus("");setGenerated(false);setPage(1);}}><RefreshCcw/>Reset</button><button className="secondary" onClick={csv}><Download/>Export CSV / Excel</button><button className="secondary" onClick={()=>window.print()}><Printer/>Print</button></div>{generated&&<><div className="mail-report-kpis">{[[rows.length,"Total corrections"],[completed,"Completed"],[`${Math.round(completed/rows.length*100)||0}%`,`On-time completion`],[overdue,"Overdue"],[`${Math.round(rejected/rows.length*100)||0}%`,`QC rejection`],[new Set(rows.map(x=>x.correctionRound)).size,"Correction rounds"]].map(x=><article key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></article>)}</div><div className="scroll"><table><thead><tr><th>Client</th><th>Project</th><th>Employee</th><th>Total</th><th>Completed</th></tr></thead><tbody>{paginatedClients.map(c=>{const set=rows.filter(x=>x.client===c);return <tr key={c}><td><b>{c}</b></td><td>{new Set(set.map(x=>x.projectId)).size} projects</td><td>{new Set(set.map(x=>x.assignedEmployee)).size} employees</td><td>{set.length}</td><td>{set.filter(x=>["QC Approved","Sent to Client","Closed"].includes(x.status)).length}</td></tr>})}</tbody></table></div>{clientList.length>0&&<Pagination currentPage={page} totalItems={clientList.length} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={setPageSize} pageSizeOptions={[5, 10, 20]} itemName="clients"/>}</>}</section>}
